### ISSUE TITLE
peers: timeouts and misreads with many messages

### ISSUE THREAD

**Issue by awlx** [DropMorePackets/haproxy-go#10]
When many stick-table entries get propagated for example during initial startup there is a problem with the message reader.

```
2024/08/13 04:18:49 reading message: invalid amount read: 30 != 22
2024/08/13 04:18:49 last message timer expired: closing connection
```

**Comment by fionera** [comment]
Fixed with https://github.com/DropMorePackets/haproxy-go/commit/278b6f11a0d2154baba563f78717d50e54fc3e67
